apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-app-config
  namespace: default
  labels:
    app: quiz-app
data:
  app.name: "quiz-app"
  app.version: "1.0.0"
  app.environment: "production"
  node.env: "production"
  port: "3000"

