apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
  namespace: default
  labels:
    app: quiz-app
spec:
  type: LoadBalancer  # Use ClusterIP for internal, NodePort for external access, LoadBalancer for cloud providers
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: quiz-app
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

